export const AUTHENTICATION_TITLE = 'Authentication';
export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST';
export const AUTHENTICATION_SIGNUP_REQUEST = 'AUTHENTICATION_SIGNUP_REQUEST';
